with-expecter: true
inpackage: false
dir: ./mocks
outpkg: mocks
mock-build-tags: "!compile"
packages:
  github.com/ksysoev/wasabi:
    interfaces:
      Dispatcher:
      RequestHandler:
      Connection:
      Request:
      Channel:
      ConnectionRegistry:
